### ISSUE TITLE
Minecraft doesn't launch after adding Lifts

### ISSUE THREAD

**Issue by Wlnfr** [lucaargolo/lifts#1]
As title said, here's the crash report. Do tell if you need more information
[crash-2021-03-02_22.31.17-client.txt](https://github.com/lucaargolo/lifts/files/6071669/crash-2021-03-02_22.31.17-client.txt)

**Comment by lucaargolo** [comment]
Hey, sorry about that, for some reason builds made in my computer were "corrupted" lol, 1.0.2 should work fine.
