### ISSUE TITLE
Taking fall damage from riding the lifts down

### ISSUE THREAD

**Issue by jpwanabe** [lucaargolo/lifts#11]
So after making a lift using the mod pack All of Fabric 3, I am taking 1 or 2 instances of fall damage on my lift. The lift is 16 blocks tall. Video attached.

https://youtu.be/-fNOSNnk73g

**Comment by lucaargolo** [comment]
For some reason, I didn't see this issue report so I'm sorry about that. This problem should be fixed in 1.1.1-BETA
