### ISSUE TITLE
Wiki Suggestion 

### ISSUE THREAD

**Issue by Wdavery** [lucaargolo/lifts#15]
For my own use I compiled a wiki page for this mod and thought it may be of use to others. All the information is taken from in-game or from your messages on Discord/CurseForge.

Preview:
---

[Showcase Video](https://www.youtube.com/watch?v=LjCs5a_9FYM)

### Lifts
Lifts are machines that can transform blocks in front of it in a platform that can move entities vertically. They can be controlled used redstone, lift buttons, and screens.

Name | Speed | Range | Input | Consumption/Block | Capacity
---:|:---:|:---:|:---:|:---:|:---:|
Stirling Lift | 1x | 16 | Burnable Fuel | 100 fuel ticks | 32 kE
Electric Lift MK1 | 1.2x | 32 | 32 E/t | 100 E | 32 kE
Electric Lift MK2 | 1.4x | 64 |  128 E/t | 100 E | 64 kE
Electric Lift MK3 | 1.6x | 128 | 512 E/t | 100 E | 128 kE
Electric Lift MK4 | 1.8x | 128 | 2048 E/t | 100 E | 256,000 kE
Electric Lift MK5 | 2x | 256 | 8192 E/t | 100 E | 512,000 kE

### Utilities
Name | Note
---:|:---:|
Lift Button | Wirelessly calls a linked lift
Screen  | Provides an interface for interacting with lifts
Screen Charger | Wirelessly charges linked screens
Linking Tool | Used to establish links between Screens, Buttons, Chargers and Lifts
Lift Detector | Emits a Redstone signal when a linked lift has its platform

### How to build a lift
- Place a lift on the ground—the yellow striped side is the platform side.
- A valid platform must:
	- have a rectangular shape
	- contain a maximum of 25 blocks
	- have a single type of block along the outer rim
- Place another lift at the desired level above or below the first, with the stripes facing the same side. (Same X and Z coordinates, different Y)
- Power all the lifts. 
	- Stirling lifts are powered by opening their GUIs and placing a burnable fuel (wood, coal, etc.)
	- Electric lifts are powered by external mods. Compatible mods include: [Tech Reborn](https://www.curseforge.com/minecraft/mc-mods/techreborn), [Industrial Revolution](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution), [Modern Industrialisation](https://modrinth.com/mod/modern-industrialization) and [Extra Generators](https://modrinth.com/mod/extra-generators)
- Move the platform by applying a redstone signal to the lift at the desired location. 
	- Mind the range limit of the lifts, and ensure they have enough power: 
		- Stirling Lifts use 100 fuel ticks per block
		- Electric lifts use 100 E per block
- The lifts can also be controlled using a `Lift Button` or `Screen`
	-  To link a `Lift Button` or `Screen` to a lift, shift-right-click a lift with a `Linking Tool` and right-click the button/screen
- Screens need energy to operate—using external mods, power them directly or link them to a powered `Screen Charger` (with a `Linking Tool`).

Raw Markdown:
---

```
[Showcase Video](https://www.youtube.com/watch?v=LjCs5a_9FYM)

### Lifts
Lifts are machines that can transform blocks in front of it in a platform that can move entities vertically. They can be controlled used redstone, lift buttons, and screens.

Name | Speed | Range | Input | Consumption/Block | Capacity
---:|:---:|:---:|:---:|:---:|:---:|
Stirling Lift | 1x | 16 | Burnable Fuel | 100 fuel ticks | 32 kE
Electric Lift MK1 | 1.2x | 32 | 32 E/t | 100 E | 32 kE
Electric Lift MK2 | 1.4x | 64 |  128 E/t | 100 E | 64 kE
Electric Lift MK3 | 1.6x | 128 | 512 E/t | 100 E | 128 kE
Electric Lift MK4 | 1.8x | 128 | 2048 E/t | 100 E | 256,000 kE
Electric Lift MK5 | 2x | 256 | 8192 E/t | 100 E | 512,000 kE

### Utilities
Name | Note
---:|:---:|
Lift Button | Wirelessly calls a linked lift
Screen  | Provides an interface for interacting with lifts
Screen Charger | Wirelessly charges linked screens
Linking Tool | Used to establish links between Screens, Buttons, Chargers and Lifts
Lift Detector | Emits a Redstone signal when a linked lift has its platform

### How to build a lift
- Place a lift on the ground—the yellow striped side is the platform side.
- A valid platform must:
	- have a rectangular shape
	- contain a maximum of 25 blocks
	- have a single type of block along the outer rim
- Place another lift at the desired level above or below the first, with the stripes facing the same side. (Same X and Z coordinates, different Y)
- Power all the lifts. 
	- Stirling lifts are powered by opening their GUIs and placing a burnable fuel (wood, coal, etc.)
	- Electric lifts are powered by external mods. Compatible mods include: [Tech Reborn](https://www.curseforge.com/minecraft/mc-mods/techreborn), [Industrial Revolution](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution), [Modern Industrialisation](https://modrinth.com/mod/modern-industrialization) and [Extra Generators](https://modrinth.com/mod/extra-generators)
- Move the platform by applying a redstone signal to the lift at the desired location. 
	- Mind the range limit of the lifts, and ensure they have enough power: 
		- Stirling Lifts use 100 fuel ticks per block
		- Electric lifts use 100 E per block
- The lifts can also be controlled using a `Lift Button` or `Screen`
	-  To link a `Lift Button` or `Screen` to a lift, shift-right-click a lift with a `Linking Tool` and right-click the button/screen
- Screens need energy to operate—using external mods, power them directly or link them to a powered `Screen Charger` (with a `Linking Tool`).
```

**Comment by lucaargolo** [comment]
Hey, thank you so much for this! I'll be setting up a Wiki in this github repository asap! Just one question, what do you think would be better? Keeping all this info on the same page or making separate pages for Lifts, Utilities and How to build a lift?

**Comment by Wdavery** [comment]
Thanks for the awesome mod, definitely an upgrade for people who love to mine! 

Personally I prefer it as a single page since it's quite compact already. Saves the user from clicking around too much.

**Comment by lucaargolo** [comment]
Cool, the wiki is now available at https://github.com/lucaargolo/lifts/wiki
Thanks again for all the work writing this!

**Comment by Wdavery** [comment]
Oops! Just noticed some typos in the first line: 
Lifts are machines that can transform blocks in front of it **into** a platform that can move entities vertically. They can be controlled **using** redstone, lift buttons, and screens.

**Comment by lucaargolo** [comment]
Fixed it!

**Comment by Wdavery** [comment]
Damn really sorry for this, I should've proofread one more time before submitting!

Left some zeros in the last column of the Lifts table by mistake.
Electric Lift MK4 - **256** kE
Electric Lift MK5 - **512** kE
