### ISSUE TITLE
[BUG] muitple floor buttons not rendering correctly

### ISSUE THREAD

**Issue by rsdworker** [lucaargolo/lifts#21]
i was setting up the lifts in my single player modded map however this a very strange happening - the texture for lift buttons are very odd

https://gyazo.com/a262781429bb747d80c122afbcd8c439

i am not sure what is problem because i have 42 mods in folder but i don't know what is problem

**Comment by lucaargolo** [comment]
It's probably optifine.

**Comment by rsdworker** [comment]
> 
> 
> It's probably optifine.

confirmed and tested with Optifine disabled and texts reappear again i will test then report to them
thanks for help :)
