### ISSUE TITLE
[BUG] Screens can't be charged in Lifts 1.3 BETA

### ISSUE THREAD

**Issue by SplendidAlakey** [lucaargolo/lifts#23]
**Minecraft** 1.17.1
**Fabric API** fabric-api-0.40.1+1.17
**Lifts** lifts-1.3-BETA+1.17

**1.** Place down a screen
**2.** Connect it to any power source

Expected result: screen charges up and prompts to link to a lift

Actual result: screen doesn't charge at all

**Comment by lucaargolo** [comment]
Huh, what power source are you connecting to?

**Comment by SplendidAlakey** [comment]
> 
> 
> Huh, what power source are you connecting to?

I tried connecting directly to Lazuli flux containers with cables (from the Industrial revolution mod) and wirelessly to a screen charger. Works on 1.2, but not 1.3.

Edit: connecting directly to a power generator (solar panel from indrev for example) also works on 1.2, but not 1.3.

**Comment by lucaargolo** [comment]
So yeah, update 1.3 is using the new version of the Energy API from TechReborn. Industrial Revolution is not yet compatible with it but it'll be very soon. For now, you should probably use a mod that's already updated to the new API like Tech Reborn itself, Modern Industrialization, or Extra Generators. Or you can downgrade the mod while you wait for indrev to update.
