### ISSUE TITLE
[Bug] Lifts not receiving energy from industrial revolution

### ISSUE THREAD

**Issue by Cavin-V** [lucaargolo/lifts#24]
After working with the Latest verison of Lifts for 1.17 (Lifts 1.3) I noticed that it doesn't seem to properly accept energy from the latest version of Industrial Revolution (Indrev 1.10.0)
However the version directly before Lifts 1.3 (Lifts 1.2) seems to accept energy from industrial revolution just fine.

Have not tested other versions of industrial revolution, but it would seem the problem is on the side of lifts.

**Comment by lucaargolo** [comment]
This is not an issue on my end. Industrial Revolution needs to update to support the new Energy Transfer API.
