### ISSUE TITLE
Poor support for Asian characters in lift screens

### ISSUE THREAD

**Issue by ChromaPIE** [lucaargolo/lifts#26]
Tried localizing the mod to simplified chinese on my own instance, the screen successfully displayed everything but restricted by the font px it uses the characters displayed are barely readable. Here's a screenshot, from it can you see that many character strokes are diluented or even vanished:
![473XM$887~YP`1RY8( KXR0](https://user-images.githubusercontent.com/56111366/142030782-0ed7599f-f6f5-4669-b024-c83e1ee79e45.png)

I believe it also happens on Japanese, Korean and so on. Would it be possible to fix this, like falling back to the default minecraft font when asian languages or stuff like that are detected?

**Comment by lucaargolo** [comment]
Huh, that's probably due to the low resolution of the screen (128x128). I'll see what I can do.

**Comment by lucaargolo** [comment]
Hello, sorry for taking too long to fix this, but I added a property in the config file called "screenScale". You can increase it to make high res fonts (Chinese, Korean, Japanese, etc) render correctly. Just beware that the screens will get more demanding to render the higher the value. Also, the values must be multiples of 2.
