### ISSUE TITLE
lifts duplicate if loading chunks while in transit

### ISSUE THREAD

**Issue by Monster-Zer0** [lucaargolo/lifts#4]
to repeat:

create a multi lift system

make lift go to a higher floor.

call lift down to a much lower level. skipping floors if need be.

run around trying to load chunks.. 

bam.. duplication.

here is a video

nothing was in the logs of any value.. neither on server or client. but I can provide if need be.

https://imgur.com/a/Sj2y0a1

**Comment by lucaargolo** [comment]
Huh, the elevator went through the "duplicated" blocks so it's probably just a visual glitch and they're probably only visible on the client. Can you confirm that? Cause if that's the case I can deploy an easy fix later today, if that's not the case and the blocks are actually being duped I'll have to further investigate this.

**Comment by Monster-Zer0** [comment]
can confirm it's client side. as a relog makes the "duplicated" blocks go away

**Comment by lucaargolo** [comment]
That should be fixed in 1.0.5.
