### ISSUE TITLE
Platforms apparently duplicate without actually duplicating >->

### ISSUE THREAD

**Issue by AlexisBloodwood** [lucaargolo/lifts#9]
Yea so, I had just come back from setting up a teleport to the end for easy dragon fighting and found that after going to my basement, the Lift platform spiritually duplicated and now the lift wont work without me dismantling and rebuilding it. Hopefully this can be fixed? I've provided a video of the issue if that helps!

https://youtu.be/hFeOaMzNVpA

**Comment by lucaargolo** [comment]
Yeah, someone reported that in the mod's official discord. Apparently, something is breaking the lifts when unloading/loading the chunks. I'll take a look and try to fix it asap!

**Comment by AlexisBloodwood** [comment]
Awesome! Thank you!

**Comment by lucaargolo** [comment]
Hey, sorry it took so long to fix this, I was kinda busy with other projects, but it should be fixed in 1.1.1-BETA
